### ISSUE TITLE
git permission-reset doesn't work when all files are staged for commit

### ISSUE THREAD

**Issue by SpacePossum** [teameh/Dotfiles#5]
```
$ git add .
$ git permission-reset 
fatal: unrecognized input
```

same when there are no pending changes.

**Comment by teameh** [comment]
Haha yeah, noticed this as well some time ago. Tnx for reporting. I'll fix this someday 😊

**Comment by teameh** [comment]
😬

**Comment by SpacePossum** [comment]
just add it to your backlog ;)
I'll have a look maybe some day, for now lets close it as a non-prio thing :)
